name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Inyectar variables de entorno
        run: cp ~/.env ./.env

      - name: Instalar dependencias
        run: |
          source ~/.bashrc
          composer install

      - name: Reiniciar servidor
        run: |
          source ~/.bashrc
          pkill -f '*/bin/php' || true
          setsid php artisan serve --port=443 --host=0.0.0.0 &